server:
  port: 8820

spring:
  application:
    name: ${adminApiModuleName}

dubbo:
  application:
    id: ${adminApiModuleName}
    name: ${adminApiModuleName}
    owner:
  protocol:
    id: dubbo
    name: dubbo
  consumer:
    group: ${dubboServiceGroup}
    version: ${dubboServiceVersion}
    timeout: 3000
  registry:
    id: ${dubboServiceProtocol}
    protocol: ${dubboServiceProtocol}
    address: ${dubboRegistryAddress}
    group: ${dubboServiceGroup}
    version: ${dubboServiceVersion}
    client: curator
  scan:
    base-packages: ${basePackage}.admin.service
