server:
  port: ${providerServicePort}

spring:
  application:
    name: ${providerModuleName}
  datasource:
    url: ${dbUrl}
    username: ${dbUsername}
    password: ${dbPassword}
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:${eurekaServerPort}/eureka/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
  type-aliases-package: ${basePackage}.mapper
