server:
  port: 8810

spring:
  application:
    name: ${providerModuleName}
  datasource:
    url: ${dbUrl}
    username: ${dbUsername}
    password: ${dbPassword}
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
  type-aliases-package: ${basePackage}.mapper

dubbo:
  application:
    id: ${providerModuleName}
    name: ${providerModuleName}
    owner:
  protocol:
    id: dubbo
    name: dubbo
  provider:
    group: ${dubboServiceGroup}
    version: ${dubboServiceVersion}
    timeout: 3000
  registry:
    id: ${dubboServiceProtocol}
    protocol: ${dubboServiceProtocol}
    address: ${dubboRegistryAddress}
    group: ${dubboServiceGroup}
    version: ${dubboServiceVersion}
    client: curator
  scan:
    base-packages: ${basePackage}.api
